/* Automatically generated by GNU msgfmt.  Do not modify!  */
package de.shellfire.vpn;
public class Messages_en extends java.util.ResourceBundle {
  private static final java.util.Hashtable table;
  static {
    java.util.Hashtable t = new java.util.Hashtable();
    t.put("","Project-Id-Version: ShellfireVPN2\nReport-Msgid-Bugs-To: \nPO-Revision-Date: \nLast-Translator: Florian Gattung <fgattung@gmail.com>\nLanguage-Team: Shellfire Team <hosting@shellfire.de>\nLanguage: en_US\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Poedit-Basepath: ../../src\nX-Poedit-SourceCharset: UTF-8\nPlural-Forms: nplurals=2; plural=n != 1;\nX-Generator: Poedit 2.0.5\nX-Poedit-KeywordsList: i18n.tr\nX-Poedit-SearchPath-0: .\n");
    t.put("Login","Login");
    t.put("Server 2","Server 2");
    t.put("Host:","Host:");
    t.put("title","title");
    t.put("Online IP:","Online IP:");
    t.put("VPN Id:","VPN Id:");
    t.put("Name","Name");
    t.put("Free","Free");
    t.put("Premium","Premium");
    t.put("Premium Plus","Premium Plus");
    t.put("256 bit","256 bit");
    t.put("192 bit","192 bit");
    t.put("128 bit","128 bit");
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    return table.get(msgid);
  }
  public java.util.Enumeration getKeys () {
    return table.keys();
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
