/* Automatically generated by GNU msgfmt.  Do not modify!  */
package de.shellfire.vpn;
public class Messages_en extends java.util.ResourceBundle {
  private static final String[] table;
  static {
    String[] t = new String[50];
    t[0] = "";
    t[1] = "Project-Id-Version: ShellfireVPN2\nReport-Msgid-Bugs-To: \nPO-Revision-Date: \nLast-Translator: Florian Gattung <fgattung@gmail.com>\nLanguage-Team: Shellfire Team <hosting@shellfire.de>\nLanguage: en_US\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Poedit-Basepath: ../../src\nX-Poedit-SourceCharset: UTF-8\nPlural-Forms: nplurals=2; plural=n != 1;\nX-Generator: Poedit 2.0.5\nX-Poedit-KeywordsList: i18n.tr\nX-Poedit-SearchPath-0: .\n";
    t[2] = "Premium Plus";
    t[3] = "Premium Plus";
    t[8] = "VPN Id:";
    t[9] = "VPN Id:";
    t[12] = "Free";
    t[13] = "Free";
    t[14] = "Host:";
    t[15] = "Host:";
    t[16] = "Online IP:";
    t[17] = "Online IP:";
    t[18] = "Name";
    t[19] = "Name";
    t[20] = "Server 2";
    t[21] = "Server 2";
    t[30] = "256 bit";
    t[31] = "256 bit";
    t[32] = "title";
    t[33] = "title";
    t[36] = "Premium";
    t[37] = "Premium";
    t[40] = "Login";
    t[41] = "Login";
    t[42] = "128 bit";
    t[43] = "128 bit";
    t[48] = "192 bit";
    t[49] = "192 bit";
    table = t;
  }
  public Object handleGetObject (String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 25) << 1;
    {
      Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 23) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 50)
        idx -= 50;
      Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 50 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 50);
        }
        public Object nextElement () {
          Object key = table[idx];
          do idx += 2; while (idx < 50 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
