/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PremiumVPNNagScreen.java
 *
 * Created on 13.07.2011, 13:44:49
 */
package de.shellfire.vpn.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import org.xnap.commons.i18n.I18n;

import de.shellfire.vpn.Util;
import de.shellfire.vpn.gui.helper.MoveMouseListener;
import de.shellfire.vpn.gui.model.VpnAttributeHeader;
import de.shellfire.vpn.gui.model.VpnComparisonTableModel;
import de.shellfire.vpn.gui.renderer.BoolImageRenderer;
import de.shellfire.vpn.gui.renderer.StarImageRenderer;
import de.shellfire.vpn.i18n.VpnI18N;
import de.shellfire.vpn.webservice.ShellfireService;
import de.shellfire.vpn.webservice.model.VpnEntry;

/**
 * 
 * @author bettmenn
 */
public class PremiumVPNNagScreen extends javax.swing.JDialog {
  private final ShellfireVPNMainForm aparent;
  private MoveMouseListener mml;

  /** Creates new form PremiumVPNNagScreen */
  public PremiumVPNNagScreen(java.awt.Frame parent, boolean modal, ActionListener al) {
    super(parent, modal);
    aparent = (ShellfireVPNMainForm) parent;
    initComponents();

    this.setLocationRelativeTo(null);
    if (al != null)
      jButton1.addActionListener(al);

    this.initComparisonTable();
    this.enableMouseMoveListener();
    this.pack();

  }

  public void disableTimer() {
    this.jLabel1.setText("");
    this.jRemainingTime.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
   * is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeaderPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jContentPanel = new javax.swing.JPanel();
        jLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRemainingTime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shellfire VPN 2");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHeaderPanel.setBackground(new java.awt.Color(18, 172, 229));
        jHeaderPanel.setName("jHeaderPanel"); // NOI18N
        jHeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(ShellfireVPNMainForm.getLogo());
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setName("jLabel6"); // NOI18N
        jHeaderPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 100));

        jContentPanel.setBackground(new java.awt.Color(64, 69, 73));
        jContentPanel.setName("jContentPanel"); // NOI18N
        jContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLoginPanel.setName("jLoginPanel"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText(i18n.tr("Verbleibende Wartezeit:"));
        jLabel1.setName("jLabel1"); // NOI18N

        jRemainingTime.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRemainingTime.setText("(remaining time)");
        jRemainingTime.setName("jRemainingTime"); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jButton1.setText(i18n.tr("Abbrechen"));
        jButton1.setName("jButton1"); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(18, 172, 229));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jTable1.setModel(new VpnComparisonTableModel());
        jTable1.setFillsViewportHeight(true);
        jTable1.setFocusable(false);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18));
        jButton2.setText(i18n.tr("Jetzt Premium kaufen"));
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemainingTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRemainingTime)))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jContentPanel.add(jLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 820, 460));

        jHeaderPanel.add(jContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 500));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>"+i18n.tr("Jetzt Upgraden auf Shellfire VPN Premium")+"</html>");
        jLabel2.setName("jLabel2"); // NOI18N
        jHeaderPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 340, 80));

        getContentPane().add(jHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
    ShellfireService service = ShellfireService.getInstance();
    Util.openUrl(service.getUrlPremiumInfo());

  }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jContentPanel;
    private javax.swing.JPanel jHeaderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JLabel jRemainingTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
  private static I18n i18n = VpnI18N.getI18n();

  void setDelay(int i) {
     String text = i + "s";
    this.jRemainingTime.setText(text);
  }

  private void initComparisonTable() {
    JTableHeader header = jTable1.getTableHeader();
    header.setReorderingAllowed(false);
    header.getColumnModel().setColumnMargin(0);
    header.setResizingAllowed(false);
    TableColumnModel columnModel = header.getColumnModel();

    for (int i = 0; i < columnModel.getColumnCount(); i++) {
      TableColumn column = jTable1.getColumnModel().getColumn(i);
      column.setHeaderRenderer(new HeaderRenderer());
    }

    TableColumnModel cm = this.jTable1.getColumnModel();
    cm.getColumn(0).setPreferredWidth(130);

    cm.getColumn(0).setCellRenderer(new RowHeaderRenderer());
    
    for (int i = 1; i < cm.getColumnCount(); i++) {
        cm.getColumn(i).setCellRenderer(new CustomRenderer());  
    }
  }

  void cleanRemove() {
    this.dispose();
    aparent.repaint();
  }

  class HeaderRenderer extends JLabel implements TableCellRenderer {
    public Component getTableCellRendererComponent(JTable table, Object value, boolean hasFocus, boolean isSelected, int row, int col) {
      setText(value.toString());
      setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
      setFont(getFont().deriveFont(15F).deriveFont(Font.BOLD));
      setBackground(new Color(18, 172, 229));
      setForeground(Color.white);
      setOpaque(true);
      setHorizontalAlignment(JLabel.CENTER);
      return this;
    }
  }

  class RowHeaderRenderer extends JLabel implements TableCellRenderer {
    public Component getTableCellRendererComponent(JTable table, Object value, boolean hasFocus, boolean isSelected, int row, int col) {
      setOpaque(true);
      setHorizontalAlignment(JLabel.RIGHT);
      setText(value.toString());
      setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
      setMinimumSize(new Dimension(getMinimumSize().width, 40));

      if (value instanceof VpnAttributeHeader) {
        jTable1.setRowHeight(row, 20);
        setFont(getFont().deriveFont(15F).deriveFont(Font.BOLD));
        setBackground(new Color(18, 172, 229));
        setForeground(Color.white);

      }

      else {
        setFont(getFont().deriveFont(12F).deriveFont(Font.PLAIN));

        setBackground(Color.white);
        setForeground(Color.black);
      }

      return this;
    }
  }

  class CustomRenderer extends JLabel implements TableCellRenderer {
    public Component getTableCellRendererComponent(JTable table, Object value, boolean hasFocus, boolean isSelected, int row, int col) {
      setOpaque(true);

      setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
      setHorizontalAlignment(JLabel.CENTER);
      
      if (value instanceof VpnEntry) {
        VpnEntry entry = (VpnEntry) value;
        if (entry.isBoolEntry()) {
          return new BoolImageRenderer().getTableCellRendererComponent(table, value, hasFocus, isSelected, row, col);
        } else if (entry.isStarEntry()) {
            return new StarImageRenderer().getTableCellRendererComponent(table, value, hasFocus, isSelected, row, col);
          } else {
          setText(entry.getText());
        }
        
      } else if (value instanceof String) {
        setText((String)value);
      }
      
      

      if (value.equals("")) {
        setBackground(new Color(18, 172, 229));
        setForeground(Color.white);
      } else {
        setBackground(Color.white);
        setForeground(Color.black);
      }

      return this;
    }
  }

  private void enableMouseMoveListener() {

    if (mml == null)
      mml = new MoveMouseListener(this);

    this.addMouseListener(mml);
    this.addMouseMotionListener(mml);

  }
}
