/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginProgressDialog.java
 *
 * Created on 13.06.2011, 15:35:22
 */
package de.shellfire.vpn.gui;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.Timer;

import org.xnap.commons.i18n.I18n;

import de.shellfire.vpn.i18n.VpnI18N;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author bettmenn
 */
public class ProgressDialog extends javax.swing.JDialog {
    private boolean option1;
    private boolean option2;
    private Runnable optionCallback;
    private static I18n i18n = VpnI18N.getI18n();

    /** Creates new form LoginProgressDialog */
    public ProgressDialog(java.awt.Frame parent, boolean modal, String text) {
        super(parent, modal);
        this.setUndecorated(true);

        initComponents();
        this.jLabel1.setText(text);
        //this.jAdditionalTextLabel.setVisible(false);
        //this.jOption2Button.setVisible(false);
        //this.jBottomLabel.setVisible(false);
        this.setLocationRelativeTo(parent); 
        this.pack();
        getContentPane().setLayout(new MigLayout("hidemode 3", "[]", "[]"));

        
        this.jProgressBar1.setIndeterminate(true);
        getContentPane().add(jProgressPanel, "cell 0 0,alignx left,aligny top");
        jProgressPanel.setLayout(new MigLayout("hidemode 3", "[grow][grow][grow]", "[][][][][][]"));
        jProgressPanel.add(jHeaderPanel, "cell 0 0 3 1,growx,aligny top");
        jProgressPanel.add(jAdditionalTextLabel, "cell 0 1,alignx left,aligny top");
        jProgressPanel.add(jProgressBar1, "cell 0 3 3 1,growx,aligny top");
        jProgressPanel.add(jLabel1, "cell 0 2 3 1,growx,aligny top");
        jProgressPanel.add(jBottomLabel, "cell 0 4 3 1,growx,aligny top");
        jProgressPanel.add(jOption1Button, "cell 0 5,growx,aligny top");
        jProgressPanel.add(jOption2Button, "cell 2 5,growx,aligny top");
    }

    public void setText(String text) {
    	this.jLabel1.setText(text);
    	this.pack();
    	this.setLocationRelativeTo(null);
    }
    
    public void updateProgress(float percentage) {
    	this.jProgressBar1.setIndeterminate(false);
    	this.jProgressBar1.setValue((int) (percentage));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jAdditionalTextLabel = new javax.swing.JLabel();
        jAdditionalTextLabel.setVisible(false);
        jOption2Button = new javax.swing.JButton();
        jOption2Button.setVisible(false);
        jOption1Button = new javax.swing.JButton();
        jOption1Button.setVisible(false);
        jBottomLabel = new javax.swing.JLabel();
        jBottomLabel.setVisible(false);
        jHeaderPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jProgressPanel.setBackground(new java.awt.Color(244, 244, 244));
        jProgressPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jProgressPanel.setName("jProgressPanel"); // NOI18N

        jLabel1.setText(i18n.tr("Einloggen...."));
        jLabel1.setName("jLabel1"); // NOI18N

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        jAdditionalTextLabel.setText("jLabel2");
        jAdditionalTextLabel.setName("jAdditionalTextLabel"); // NOI18N

        jOption2Button.setText("jButton1");
        jOption2Button.setName("jOption2Button"); // NOI18N
        jOption2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOption2ButtonActionPerformed(evt);
            }
        });

        jOption1Button.setText("jButton1");
        jOption1Button.setName("jOption1Button"); // NOI18N
        jOption1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOption1ButtonActionPerformed(evt);
            }
        });

        jBottomLabel.setText("jLabel2");
        jBottomLabel.setName("jBottomLabel"); // NOI18N

        jHeaderPanel.setBackground(new java.awt.Color(18, 172, 229));
        jHeaderPanel.setName("jHeaderPanel");
        jHeaderPanel.setLayout(new MigLayout("", "[]", "[]"));

        jLabel5.setIcon(ShellfireVPNMainForm.getLogo());
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setName("jLabel5"); // NOI18N
        jHeaderPanel.add(jLabel5, "cell 0 0,grow");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOption2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOption2ButtonActionPerformed
        this.option2 = true;
        setVisible(false);
        this.callOptionCallback();
    }//GEN-LAST:event_jOption2ButtonActionPerformed

    private void jOption1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOption1ButtonActionPerformed
        this.option1 = true;
        setVisible(false);
        this.callOptionCallback();
    }//GEN-LAST:event_jOption1ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdditionalTextLabel;
    private javax.swing.JLabel jBottomLabel;
    private javax.swing.JPanel jHeaderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jOption1Button;
    private javax.swing.JButton jOption2Button;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel jProgressPanel;
    // End of variables declaration//GEN-END:variables

    void addInfo(String text) {
        this.setTextAndShowComponent(this.jAdditionalTextLabel, text);
    }


    
    void setTextAndShowComponent(JLabel component, String text) {
        component.setText(text);
        component.setVisible(true);
        this.pack();        
        this.setLocationRelativeTo(null);
    }
    void setTextAndShowComponent(JButton component, String text) {
        component.setText(text);
        component.setVisible(true);
        component.setEnabled(false);
        this.pack();        
        this.setLocationRelativeTo(null);
    }


    void addBottomText(String text) {
        this.setTextAndShowComponent(this.jBottomLabel, text);
    }

    public void setOption(int i, String text) {
        this.setOption(i, text, 0);        
    }

    void setOption(int i, final String text, int waitTime) {
      JButton button = null;
      if (i == 1) {
        button = jOption1Button;
      } else if (i == 2) {
        button = jOption2Button;
      }

      
      class OptionListener implements ActionListener {
        private JButton button;
        private String text;
        public OptionListener(JButton b, String t) {
          this.button = b;
          this.text = t;
        }
        
        @Override
        public void actionPerformed(ActionEvent e) {
          this.button.setEnabled(true);
        }
      };
      setTextAndShowComponent(button, text);
      Timer t = new Timer(waitTime*1000, new OptionListener(button, text));
      t.setRepeats(false);
      t.start();
  }

    public boolean isOption1() {
        return option1;
    }
    public boolean isOption2() {
        return option2;
    }

    public void setOptionCallback(Runnable runnable) {
        this.optionCallback = runnable;
    }

    private void callOptionCallback() {
        if (this.optionCallback != null);
            this.optionCallback.run();
    }

	public void setIndeterminate(boolean b) {
		jProgressBar1.setIndeterminate(b);
		
	}


}
