/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpgradeDialog.java
 *
 * Created on 09.08.2011, 20:21:54
 */
package de.shellfire.vpn.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;

import javax.swing.JTextField;

import org.xnap.commons.i18n.I18n;

import de.shellfire.vpn.Util;
import de.shellfire.vpn.gui.helper.Max2CharDocument;
import de.shellfire.vpn.gui.helper.Max4CharDocument;
import de.shellfire.vpn.gui.helper.MoveMouseListener;
import de.shellfire.vpn.i18n.VpnI18N;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author bettmenn
 */
public class UpgradeDialog extends javax.swing.JDialog {

  private static I18n i18n = VpnI18N.getI18n();
    private String productKey;
  
    /** Creates new form UpgradeDialog */
    public UpgradeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        MoveMouseListener mml = new MoveMouseListener(this);
        this.addMouseListener(mml);
        this.addMouseMotionListener(mml);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        setBounds(0,0,screenSize.width, screenSize.height);
        this.setLocationRelativeTo(null);
        this.pack();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLoginPanel = new javax.swing.JPanel();
        jLabelEmailAddress = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPerformUpgradeButton = new javax.swing.JButton();
        productKey1 = new javax.swing.JTextField();
        productKey2 = new javax.swing.JTextField();
        productKey3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jHeaderPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shellfire VPN");

        jPanel7.setBackground(new java.awt.Color(64, 69, 73));
        jPanel7.setName("jPanel7");

        jLoginPanel.setName("jLoginPanel");
        jLoginPanel.setLayout(new MigLayout("", "[grow][][][][grow][][][][grow]", "[][][][]"));

        jLabelEmailAddress.setFont(new java.awt.Font("Arial", 0, Util.getFontSize())); // NOI18N
        jLabelEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmailAddress.setText("<html>"+i18n.tr("Gib hier den bereits erworbenen Produktschlüssel ein, um das<br> Upgrade zur Premium oder Premium-Plus Version durchzuführen.")+"</html>");
        jLabelEmailAddress.setName("jLabelEmailAddress"); // NOI18N
        jLoginPanel.add(jLabelEmailAddress, "cell 0 1 9 1,grow");

        jLabel16.setFont(new java.awt.Font("Arial", 1, Util.getFontSize()*2)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText(i18n.tr("produktschlüssel eingeben"));
        jLabel16.setName("jLabel16"); // NOI18N
        jLoginPanel.add(jLabel16, "cell 0 0 9 1,grow");

        jPerformUpgradeButton.setText(i18n.tr("Jetzt Upgraden"));
        jPerformUpgradeButton.setName("jPerformUpgradeButton"); // NOI18N
        jPerformUpgradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPerformUpgradeButtonActionPerformed(evt);
            }
        });
        jLoginPanel.add(jPerformUpgradeButton, "cell 0 3 9 1,alignx center,aligny top");

        productKey1.setDocument(new Max2CharDocument());
        productKey1.setFont(new java.awt.Font("Courier New", 0, (int) (Util.getFontSize()*1.5))); // NOI18N
        productKey1.setName("productKey1"); // NOI18N
        jLoginPanel.add(productKey1, "cell 0 2,grow");

        productKey2.setDocument(new Max4CharDocument());
        productKey2.setFont(new java.awt.Font("Courier New", 0, (int) (Util.getFontSize()*1.5))); // NOI18N
        productKey2.setName("productKey2"); // NOI18N
        productKey2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productKey2FocusGained(evt);
            }
        });
        getContentPane().setLayout(new MigLayout("", "[]", "[][]"));
        jPanel7.setLayout(new MigLayout("", "[grow]", "[grow]"));
        jLoginPanel.add(productKey2, "cell 4 2,grow");

        productKey3.setDocument(new Max4CharDocument());
        productKey3.setFont(new java.awt.Font("Courier New", 0, (int) (Util.getFontSize()*1.5))); // NOI18N
        productKey3.setName("productKey3"); // NOI18N
        jLoginPanel.add(productKey3, "cell 8 2,grow");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, (int) (Util.getFontSize()*1.6))); // NOI18N
        jLabel2.setText("-");
        jLabel2.setName("jLabel2"); // NOI18N
        jLoginPanel.add(jLabel2, "cell 2 2,growx,aligny center");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, (int) (Util.getFontSize()*1.6))); // NOI18N
        jLabel3.setText("-");
        jLabel3.setName("jLabel3"); // NOI18N
        jLoginPanel.add(jLabel3, "cell 6 2,growx,aligny center");

        jPanel7.add(jLoginPanel, "cell 0 0,grow");

        getContentPane().add(jPanel7, "cell 0 1,growx,aligny bottom");

        jHeaderPanel.setBackground(new java.awt.Color(18, 172, 229));
        jHeaderPanel.setName("jHeaderPanel");
        jHeaderPanel.setLayout(new MigLayout("", "[grow][grow]", "[grow]"));

        jLabel5.setIcon(ShellfireVPNMainForm.getLogo());
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setName("jLabel5"); // NOI18N
        jHeaderPanel.add(jLabel5, "cell 0 0,alignx left,growy");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setName("jPanel6");

        jLabel6.setFont(new java.awt.Font("Arial", 0, Util.getFontSize())); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(Util.getImageIcon("/icons/exit.png")); // NOI18N
        jLabel6.setText(i18n.tr("zurück"));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new MigLayout("", "[100px]", "[30px]"));
        jPanel6.add(jLabel6, "cell 0 0,grow");

        jHeaderPanel.add(jPanel6, "cell 1 0,alignx left,aligny top");

        getContentPane().add(jHeaderPanel, "cell 0 0,alignx left,aligny top");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        
}//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(Color.LIGHT_GRAY);
}//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(Color.white);
}//GEN-LAST:event_jLabel6MouseExited


    //TODO: Disable button, remove button or dialog that says: no upgrad possible currently, or go directly to website
    private void jPerformUpgradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPerformUpgradeButtonActionPerformed
      String key = productKey1.getText()  + "-" + productKey2.getText()  + "-" + productKey3.getText();

      //performUpgrade(key);
        
    }//GEN-LAST:event_jPerformUpgradeButtonActionPerformed
/*
    private void performUpgrade(String key) {
      
      ProgressDialog upgradeProgressDialog = new ProgressDialog(null, false, i18n.tr("Produktschlüssel wird überprüft..."));
      upgradeProgressDialog.setVisible(true);
      
      ShellfireService shellfire = (ShellfireService)Storage.get(ShellfireService.class);
      WsUpgradeResult result = shellfire.upgradeVpnToPremiumWithSerial(key);
      
      upgradeProgressDialog.dispose();
      
      
      if (result != null && result.getUpgradeSuccesful() == 0) {
        JOptionPane.showMessageDialog(null, i18n.tr("Produktschlüssel ungültig:") + " " + key, i18n.tr("Fehler"), JOptionPane.ERROR_MESSAGE);
      } else if (result.getUpgradeSuccesful() == 1) {
        String msg = i18n.tr("Produktschlüssel erfolgreich eingelöst!") + "\n\n";
        msg += i18n.tr("VPN Typ:") + " " + result.getEAccountType() + "\n";
        
        long until = (long)result.getIUpgradeUntil() *1000;
        
        Date upgradeUntil = new Date(until);
        SimpleDateFormat df = new SimpleDateFormat(i18n.tr("d. MMMM yyyy"), VpnI18N.getLanguage().getLocale());
        String dt = df.format(upgradeUntil);        
        
        msg += i18n.tr("Gültig bis:") + " " + dt + "\n\n";
        
        msg += i18n.tr("Um dein Upgrade zu aktivieren, muss   neu gestartet werden.") + "\n\n";
        msg += i18n.tr("Shellfire VPN jetzt neu starten?");
        
        
        int res = JOptionPane.showConfirmDialog(null, msg, i18n.tr("Produktschlüssel erfolgreich eingelöst"), JOptionPane.YES_NO_OPTION);
        
        this.dispose();

        if (res == JOptionPane.YES_OPTION) {
          LoginForm.restart();
        }
      }
      
    }
*/
    private void productKey2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productKey2FocusGained
        jumpToStart(evt);
    }//GEN-LAST:event_productKey2FocusGained

    public String getProductKey() {
        return this.productKey;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jHeaderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEmailAddress;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jPerformUpgradeButton;
    private javax.swing.JTextField productKey1;
    private javax.swing.JTextField productKey2;
    private javax.swing.JTextField productKey3;
    // End of variables declaration//GEN-END:variables



    private void jumpToStart(FocusEvent evt) {
        JTextField textField = (JTextField) evt.getSource();
        textField.setCaretPosition(0);
    }
}
