/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VpnSelectDialog2.java
 *
 * Created on 21.07.2011, 09:19:21
 */
package de.shellfire.vpn.gui;

import java.awt.Color;
import java.awt.Image;
import java.util.LinkedList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

import org.slf4j.Logger;
import org.xnap.commons.i18n.I18n;

import de.shellfire.vpn.Util;
import de.shellfire.vpn.VpnProperties;
import de.shellfire.vpn.exception.VpnException;
import de.shellfire.vpn.gui.helper.MoveMouseListener;
import de.shellfire.vpn.gui.model.VpnSelectionTableModel;
import de.shellfire.vpn.i18n.VpnI18N;
import de.shellfire.vpn.webservice.Vpn;
import de.shellfire.vpn.webservice.WebService;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author bettmenn
 */
public class VpnSelectDialog extends javax.swing.JFrame {
  private static Logger log = Util.getLogger(VpnSelectDialog.class.getCanonicalName());
  private static final long serialVersionUID = 1L;
  private final LoginForm parentFrame;
  private VpnSelectionTableModel vpnSelectionTableModel;
  private final WebService service;
  private boolean autoConnect;
  public static final String REG_REMEMBERSELECTION = "SelectedVpnId";
  private static I18n i18n = VpnI18N.getI18n();

  VpnSelectDialog(LoginForm parent, WebService service, boolean autoConnect) {
    this.parentFrame = parent;
    this.service = service;
    this.autoConnect = autoConnect;
    this.setUndecorated(true);
    MoveMouseListener mml = new MoveMouseListener(this);
    this.addMouseListener(mml);
    this.addMouseMotionListener(mml);
    this.loadIcon();

    initComponents();

    this.initVpnSelectTable(service.getAllVpn());
    this.setLocationRelativeTo(null);
    this.pack();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
   * is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel6 = new javax.swing.JPanel();
    jBackLabel = new javax.swing.JLabel();
    jHeaderPanel = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();
    jSelectVpnPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jSelectButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jVpnSelectTable = new javax.swing.JTable();
    jRememberSelection = new javax.swing.JCheckBox();
    jLabel16 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jPanel6.setBackground(new java.awt.Color(0, 0, 0));
    jPanel6.setName("jPanel6");

    jBackLabel.setFont(new java.awt.Font("Arial", 0, Util.getFontSize()));
    jBackLabel.setForeground(new java.awt.Color(255, 255, 255));
    jBackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jBackLabel.setIcon(Util.getImageIcon("/icons/exit.png")); // NOI18N
    jBackLabel.setText(i18n.tr("back"));
    jBackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jBackLabel.setName("jBackLabel"); // NOI18N
    jBackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jBackLabelMouseClicked(evt);
      }

      public void mouseEntered(java.awt.event.MouseEvent evt) {
        jBackLabelMouseEntered(evt);
      }

      public void mouseExited(java.awt.event.MouseEvent evt) {
        jBackLabelMouseExited(evt);
      }
    });
    jPanel6.setLayout(new MigLayout("", "[]", "[]"));
    jPanel6.add(jBackLabel, "cell 0 0,grow");

    jHeaderPanel.setBackground(new java.awt.Color(18, 172, 229));
    jHeaderPanel.setName("jHeaderPanel");
    jHeaderPanel.setLayout(new MigLayout("", "[grow][]", "[]"));

    jLabel5.setIcon(ShellfireVPNMainForm.getLogo());
    jLabel5.setAlignmentY(0.0F);
    jLabel5.setName("jLabel5"); // NOI18N
    jHeaderPanel.add(jLabel5, "cell 0 0,grow");
    jHeaderPanel.add(jPanel6, "alignx right,aligny top");
    // jHeaderPanel.add(jLabel5, "cell 0 0,grow");

    jPanel7.setBackground(new java.awt.Color(64, 69, 73));
    jPanel7.setName("jPanel7");

    jSelectVpnPanel.setName("jSelectVpnPanel"); // NOI18N

    jLabel1.setText(i18n.tr(
        "<html>Multiple VPN are located in your Shellfire account.<br />Please select the VPN you want to use</html>"));
    jLabel1.setName("jLabel1"); // NOI18N

    jSelectButton.setText(i18n.tr("select VPN"));
    jSelectButton.setName("jSelectButton"); // NOI18N
    jSelectButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jSelectButtonActionPerformed(evt);
      }
    });
    jPanel7.setLayout(new MigLayout("", "[]", "[]"));

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jVpnSelectTable.setFont(new java.awt.Font("Lucida Grande", 0, Util.getFontSize())); // NOI18N
    jVpnSelectTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } },
        new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
    jVpnSelectTable.setAutoCreateRowSorter(true);
    jVpnSelectTable.setFocusable(false);
    jVpnSelectTable.setGridColor(new java.awt.Color(64, 69, 73));
    jVpnSelectTable.setName("jVpnSelectTable"); // NOI18N
    jScrollPane1.setViewportView(jVpnSelectTable);

    jRememberSelection.setSelected(true);
    jRememberSelection.setText(i18n.tr("Save my choice"));
    jRememberSelection.setName("jRememberSelection"); // NOI18N

    jLabel16.setFont(new java.awt.Font("Arial", 1, Util.getFontSize() * 2));
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel16.setText(i18n.tr("vpn choice"));
    jLabel16.setName("jLabel16"); // NOI18N

    jLabel3.setText(i18n.tr(
        "<html>Note: VPN types PPTP and L2TP/IPSec<br>have to be switched to OpenVPN before<br>you can connect using sf vpn.</html>"));
    jLabel3.setName("jLabel3");

    jPanel7.add(jSelectVpnPanel, "cell 0 0,growx,aligny top");
    jSelectVpnPanel.setLayout(new MigLayout("", "[]", "[][][][][][]"));
    jSelectVpnPanel.add(jLabel16, "cell 0 0,grow");
    jSelectVpnPanel.add(jLabel1, "cell 0 1,alignx left,growy");
    jSelectVpnPanel.add(jRememberSelection, "cell 0 3,grow");
    jSelectVpnPanel.add(jLabel3, "cell 0 5,grow");
    jSelectVpnPanel.add(jScrollPane1, "cell 0 2,grow");
    jSelectVpnPanel.add(jSelectButton, "cell 0 4,growx,aligny top");
    getContentPane().setLayout(new MigLayout("", "[][]", "[][]"));

    getContentPane().add(jHeaderPanel, "cell 0 0,grow");
    getContentPane().add(jPanel7, "cell 0 1,grow");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jBackLabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jBackLabelMouseClicked
    parentFrame.setVisible(true);
    this.setVisible(false);
  }// GEN-LAST:event_jBackLabelMouseClicked

  private void jBackLabelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jBackLabelMouseEntered
    jBackLabel.setForeground(Color.LIGHT_GRAY);
  }// GEN-LAST:event_jBackLabelMouseEntered

  private void jBackLabelMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jBackLabelMouseExited
    jBackLabel.setForeground(Color.white);
  }// GEN-LAST:event_jBackLabelMouseExited

  private void jSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jSelectButtonActionPerformed
    try {
      int selected = this.jVpnSelectTable.getSelectedRow();
      if (selected == -1) {
        JOptionPane.showMessageDialog(null, i18n.tr("Please select a VPN from the list to proceed"), i18n.tr("No VPN selected"),
            JOptionPane.ERROR_MESSAGE);
      } else {
        Vpn selectedVpn = this.vpnSelectionTableModel.getVpn(selected);
        rememberSelectionIfDesired(selectedVpn);

        this.service.selectVpn(selectedVpn);
        this.setVisible(false);
        ShellfireVPNMainForm mainForm = new ShellfireVPNMainForm(service);
        mainForm.setVisible(true);
        mainForm.afterLogin(autoConnect);

      }
    } catch (VpnException ex) {
      Util.handleException(ex);
    }

  }// GEN-LAST:event_jSelectButtonActionPerformed

  private void initVpnSelectTable(LinkedList<Vpn> allVpn) {
    vpnSelectionTableModel = new VpnSelectionTableModel(allVpn);

    this.jVpnSelectTable.setModel(vpnSelectionTableModel);
    TableColumnModel cm = this.jVpnSelectTable.getColumnModel();

    cm.getColumn(0).setPreferredWidth(70);
    cm.getColumn(1).setPreferredWidth(100);
    cm.getColumn(2).setPreferredWidth(180);
    this.jVpnSelectTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    this.jVpnSelectTable.getTableHeader().setReorderingAllowed(false);

    for (int row = 0; row < jVpnSelectTable.getRowCount(); row++) {
      jVpnSelectTable.setRowHeight(row, 40);
    }

    // jScrollPane1.getViewport().setBackground(new Color(224, 224, 226));

  }

  private void loadIcon() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/sfvpn2-idle.png"));
    Image img = icon.getImage();

    setIconImage(img);

  }

  private void rememberSelectionIfDesired(Vpn selectedVpn) {
    VpnProperties props = VpnProperties.getInstance();
    if (jRememberSelection.isSelected()) {

      int vpnId = selectedVpn.getVpnId();
      log.debug("Remembering Vpn ID:" + vpnId);

      props.setInt(REG_REMEMBERSELECTION, vpnId);
    } else {
      log.debug("Forgetting vpn selections");
      props.setInt(REG_REMEMBERSELECTION, 0);
    }
  }

  public int rememberedVpnSelection() {
    VpnProperties props = VpnProperties.getInstance();
    int remembered = props.getInt(REG_REMEMBERSELECTION, 0);

    return remembered;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jBackLabel;
  private javax.swing.JPanel jHeaderPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JCheckBox jRememberSelection;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton jSelectButton;
  private javax.swing.JPanel jSelectVpnPanel;
  private javax.swing.JTable jVpnSelectTable;
  // End of variables declaration//GEN-END:variables
}
