/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OwnPositionPanel.java
 *
 * Created on 19.06.2011, 12:31:18
 */
package de.shellfire.vpn.gui.model;

import org.xnap.commons.i18n.I18n;

import de.shellfire.vpn.i18n.VpnI18N;
import de.shellfire.vpn.types.LocatableIcon;

/**
 *
 * @author bettmenn
 */
public class OwnPositionPanel extends javax.swing.JPanel {
    private static I18n i18n = VpnI18N.getI18n();
    
    /** Creates new form OwnPositionPanel */
    public OwnPositionPanel(LocatableIcon icon) {
        initComponents();
        
        this.jCityLabel.setText(icon.getCity());
        this.jCountryLabel.setText(icon.getCountryString());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOwnPlaceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCountryLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCityLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jOwnPlaceLabel.setBackground(new java.awt.Color(18, 172, 229));
        jOwnPlaceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jOwnPlaceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jOwnPlaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jOwnPlaceLabel.setText(i18n.tr("Eigener Standort"));
        jOwnPlaceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jOwnPlaceLabel.setName("jOwnPlaceLabel"); // NOI18N
        jOwnPlaceLabel.setOpaque(true);
        add(jOwnPlaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel2.setText(i18n.tr("Land:"));
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jCountryLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jCountryLabel.setText("de");
        jCountryLabel.setName("jCountryLabel"); // NOI18N
        add(jCountryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel1.setText(i18n.tr("Stadt:"));
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCityLabel.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jCityLabel.setText("xxx");
        jCityLabel.setName("jCityLabel"); // NOI18N
        add(jCityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(224, 224, 226));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 170, 60));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCityLabel;
    private javax.swing.JLabel jCountryLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jOwnPlaceLabel;
    // End of variables declaration//GEN-END:variables
}
